apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: amazeeio-openshift-template-configmap
parameters:
  - name: SAFE_BRANCH
    description: Which branch this belongs to, special chars replaced with dashes
    required: true
  - name: SAFE_PROJECT
    description: Which project this belongs to, special chars replaced with dashes
    required: true
  - name: BRANCH
    description: Which branch this belongs to, original value
    required: true
  - name: PROJECT
    description: Which project this belongs to, original value
    required: true
  - name: AMAZEEIO_GIT_SHA
    description: git hash sha of the current deployment
    required: true
objects:
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: amazeeio-env
  data:
    AMAZEEIO_GIT_SAFE_BRANCH: ${SAFE_BRANCH}
    AMAZEEIO_GIT_BRANCH: ${BRANCH}
    AMAZEEIO_SAFE_PROJECT: ${SAFE_PROJECT}
    AMAZEEIO_GIT_SHA: ${AMAZEEIO_GIT_SHA}
    AMAZEEIO_PROJECT: ${PROJECT}