apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: lagoon-openshift-template-configmap
parameters:
  - name: SAFE_BRANCH
    description: Which branch this belongs to, special chars replaced with dashes
    required: true
  - name: SAFE_PROJECT
    description: Which project this belongs to, special chars replaced with dashes
    required: true
  - name: BRANCH
    description: Which branch this belongs to, original value
    required: true
  - name: PROJECT
    description: Which project this belongs to, original value
    required: true
  - name: LAGOON_GIT_SHA
    description: git hash sha of the current deployment
    required: true
objects:
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: lagoon-env
  data:
    LAGOON_GIT_SAFE_BRANCH: ${SAFE_BRANCH}
    LAGOON_GIT_BRANCH: ${BRANCH}
    LAGOON_SAFE_PROJECT: ${SAFE_PROJECT}
    LAGOON_GIT_SHA: ${LAGOON_GIT_SHA}
    LAGOON_PROJECT: ${PROJECT}