apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: lagoon-openshift-template-configmap
parameters:
  - name: SAFE_BRANCH
    description: Which branch this belongs to, special chars replaced with dashes
    required: true
  - name: SAFE_PROJECT
    description: Which project this belongs to, special chars replaced with dashes
    required: true
  - name: BRANCH
    description: Which branch this belongs to, original value
    required: true
  - name: PROJECT
    description: Which project this belongs to, original value
    required: true
  - name: ENVIRONMENT_TYPE
    description: Which environment type this project is
    value: development
  - name: ROUTE
    description: The main route of this project
    value: ""
  - name: ROUTES
    description: All routes of this project
    value: ""
objects:
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: lagoon-env
  data:
    LAGOON_GIT_SAFE_BRANCH: ${SAFE_BRANCH}
    LAGOON_GIT_BRANCH: ${BRANCH}
    LAGOON_SAFE_PROJECT: ${SAFE_PROJECT}
    LAGOON_PROJECT: ${PROJECT}
    LAGOON_ENVIRONMENT_TYPE: ${ENVIRONMENT_TYPE}
    LAGOON_ROUTE: ${ROUTE}
    LAGOON_ROUTES: ${ROUTES}