apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: amazeeio-openshift-template-nginx
parameters:
  - name: SERVICE_NAME
    description: Name of this service
    required: true
  - name: SAFE_BRANCH
    description: Which branch this belongs to, special chars replaced with dashes
    required: true
  - name: SAFE_SITEGROUP
    description: Which sitegroup this belongs to, special chars replaced with dashes
    required: true
  - name: BRANCH
    description: Which branch this belongs to, original value
    required: true
  - name: SITEGROUP
    description: Which sitegroup this belongs to, original value
    required: true
  - name: AMAZEEIO_GIT_SHA
    description: git hash sha of the current deployment
    required: true
  - name: SERVICE_ROUTER_URL
    description: URL of the Router for this service
    value: ""
  - name: PROJECT
    description: Name of the Project that this service is in
    required: true
  - name: REGISTRY
    description: Registry where Images are pushed to
    required: true
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      branch: ${SAFE_BRANCH}
      sitegroup: ${SAFE_SITEGROUP}
    name: ${SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      service: ${SERVICE_NAME}
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: ${SERVICE_NAME}
          branch: ${SAFE_BRANCH}
          sitegroup: ${SAFE_SITEGROUP}
      spec:
        containers:
        - image: ${REGISTRY}/${PROJECT}/${SERVICE_NAME}:latest
          name: ${SERVICE_NAME}
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /nginx_status
              port: 50000
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /nginx_status
              port: 50000
            initialDelaySeconds: 90
            timeoutSeconds: 3
            failureThreshold: 5
          env:
            - name: AMAZEEIO_GIT_BRANCH
              valueFrom:
                configMapKeyRef:
                  name: amazeeio-env
                  key: AMAZEEIO_GIT_BRANCH
            - name: AMAZEEIO_GIT_SAFE_BRANCH
              valueFrom:
                configMapKeyRef:
                  name: amazeeio-env
                  key: AMAZEEIO_GIT_SAFE_BRANCH
            - name: AMAZEEIO_GIT_SHA
              valueFrom:
                configMapKeyRef:
                  name: amazeeio-env
                  key: AMAZEEIO_GIT_SHA
            - name: AMAZEEIO_SITEGROUP
              valueFrom:
                configMapKeyRef:
                  name: amazeeio-env
                  key: AMAZEEIO_SITEGROUP
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${SERVICE_NAME}
        from:
          kind: ImageStreamTag
          name: ${SERVICE_NAME}:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      service: ${SERVICE_NAME}
      branch: ${SAFE_BRANCH}
      sitegroup: ${SAFE_SITEGROUP}
    name: ${SERVICE_NAME}
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      service: ${SERVICE_NAME}
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      service: ${SERVICE_NAME}
      branch: ${SAFE_BRANCH}
      sitegroup: ${SAFE_SITEGROUP}
    name: ${SERVICE_NAME}
  spec:
    host: ${SERVICE_ROUTER_URL}
    port:
      targetPort: http
    to:
      kind: Service
      name: ${SERVICE_NAME}